# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yohoo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

# 不拦截地址
exclude_path: /css/**,/docs/**,/fonts/**,/img/**,/js/**,/plugin/**,/plugins/**,/index/login,/index/index,/adminMenu/treeList

# 附件上传地址
upload_path: /home/upload/

# 微信支付证书
cert_path: D:/1524609681_20190226_cert/apiclient_cert.p12

# img domain_name
domain_name: http://images.iguangj.cn/

# 端口
#server:
#  port: 8080
#  servlet:
#    context-path: /yohoo

# MyBatis配置
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 自定义参数
customParm: linxi